name = "glugify"
version = "1.0.1"
description = "A robust, type-safe slugification library for Gleam that converts text into URL-friendly slugs"
licences = ["Apache-2.0"]
repository = { type = "github", user = "anima-international", repo = "glugify" }
links = [
  { title = "Documentation", href = "https://hexdocs.pm/glugify" },
  { title = "Changelog", href = "https://github.com/anima-international/glugify/blob/main/CHANGELOG.md" }
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.0 and < 2.0.0"
