#!/usr/bin/env python3
"""Generates src/glugify/internal/char_maps.gleam from dev/char_data/*.tsv.

The TSV files are the source of truth for the transliteration tables.
Each line is `grapheme<TAB>replacement`; lines starting with `#` become
comments in the generated code, and graphemes written as `U+XXXX` are
emitted as `\\u{XXXX}` escapes (used for whitespace and other invisible
characters). Consecutive lines with the same replacement are grouped
into one pattern (`"a" | "b" -> Ok("x")`).

Run from the repo root, then format:

    python3 dev/tools/generate_char_maps.py
    gleam format src

To add a new script (e.g. CJK pinyin), add a TSV file, register it in
TABLES below, and add a branch to the dispatcher in lookup().
"""

import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
DATA = os.path.join(ROOT, "dev", "char_data")
OUT = os.path.join(ROOT, "src", "glugify", "internal", "char_maps.gleam")

# (table name, doc comment lines)
TABLES = [
    ("latin", ["Latin-1 Supplement and Latin Extended-A/B characters."]),
    (
        "cyrillic",
        [
            "Cyrillic characters (Russian alphabet plus common Ukrainian and",
            "Belarusian letters), using a common romanization scheme.",
        ],
    ),
    ("greek", ["Greek characters (modern Greek romanization)."]),
    (
        "arabic",
        [
            "Arabic and Persian characters, using a basic consonantal romanization",
            "(vowel marks are dropped, as in other slugify libraries).",
        ],
    ),
    (
        "hebrew",
        [
            "Hebrew characters, using a basic consonantal romanization",
            "(niqqud vowel points are dropped).",
        ],
    ),
    (
        "punctuation",
        [
            "Typographic punctuation commonly produced by word processors and CMSes.",
            "",
            "Apostrophe-like characters map to the empty string so contractions",
            'stay joined ("don’t" becomes "dont"); everything else maps to a space,',
            "which later becomes a separator.",
        ],
    ),
    ("symbol", ["Currency signs and common symbols, mapped to words."]),
]

HEADER = '''\
/// Character lookup tables for transliteration.
///
/// GENERATED by dev/tools/generate_char_maps.py from dev/char_data/*.tsv —
/// edit the TSV files and regenerate instead of editing this file.
///
/// Lookups are implemented as case expressions rather than dictionaries so
/// the compiler can produce constant-time jump tables with no per-call
/// allocation (a `dict.Dict` would need to be rebuilt on every call, since
/// Gleam constants cannot hold computed values).
import glugify/locale.{type Locale}
'''


def gleam_grapheme(g):
    if re.fullmatch(r"U\+[0-9A-F]+", g):
        return '"\\u{%s}"' % g[2:]
    return '"%s"' % g.replace("\\", "\\\\").replace('"', '\\"')


def read_rows(name):
    """Returns a list of ('comment', text) | ('map', grapheme, replacement)."""
    rows = []
    with open(os.path.join(DATA, name + ".tsv"), encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line.strip():
                rows.append(("break",))
                continue
            if line.startswith("#"):
                rows.append(("comment", line[1:].strip()))
            else:
                grapheme, _, replacement = line.partition("\t")
                rows.append(("map", grapheme, replacement))
    return rows


def grouped_arms(rows, indent):
    """Groups consecutive mappings with the same replacement into one arm."""
    out = []
    group = []
    repl = None

    def flush():
        if group:
            alts = " | ".join(gleam_grapheme(g) for g in group)
            out.append('%s%s -> Ok("%s")' % (indent, alts, repl))
            group.clear()

    for row in rows:
        if row[0] == "break":
            flush()
            repl = None
        elif row[0] == "comment":
            flush()
            repl = None
            out.append("%s// %s" % (indent, row[1]))
        else:
            _, grapheme, replacement = row
            if replacement != repl:
                flush()
                repl = replacement
            group.append(grapheme)
    flush()
    return out


def table_fn(name, doc):
    lines = []
    for d in doc:
        lines.append(("/// " + d).rstrip())
    lines.append("pub fn lookup_%s(grapheme: String) -> Result(String, Nil) {" % name)
    lines.append("  case grapheme {")
    lines.extend(grouped_arms(read_rows(name), "    "))
    lines.append("    _ -> Error(Nil)")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines)


def locale_case(name, indent):
    rows = [r for r in read_rows(name) if r[0] == "map"]
    lines = ["%scase grapheme {" % indent]
    for _, grapheme, replacement in rows:
        lines.append('%s  %s -> Ok("%s")' % (indent, gleam_grapheme(grapheme), replacement))
    lines.append("%s  _ -> Error(Nil)" % indent)
    lines.append("%s}" % indent)
    return "\n".join(lines)


def dispatcher():
    doc = [
        "/// Looks up the ASCII transliteration for a single grapheme.",
        "///",
        "/// Checks, in order: Latin extended characters, Cyrillic, Greek,",
        "/// punctuation/whitespace, and symbols. Returns `Error(Nil)` when the",
        "/// grapheme has no known mapping.",
    ]
    names = [name for name, _ in TABLES]
    body = "lookup_%s(grapheme)" % names[-1]
    for name in reversed(names[:-1]):
        body = (
            "case lookup_%s(grapheme) {\n"
            "    Ok(replacement) -> Ok(replacement)\n"
            "    Error(Nil) -> %s\n"
            "  }" % (name, body.replace("\n", "\n  "))
        )
    return "\n".join(doc) + (
        "\npub fn lookup(grapheme: String) -> Result(String, Nil) {\n  %s\n}" % body
    )


def locale_fn():
    return "\n".join(
        [
            "/// Locale-specific transliterations, checked before the general tables.",
            "pub fn lookup_locale(grapheme: String, locale: Locale) -> Result(String, Nil) {",
            "  case locale {",
            "    locale.German ->",
            locale_case("locale_german", "      "),
            "    locale.Danish | locale.Norwegian ->",
            locale_case("locale_danish_norwegian", "      "),
            "    locale.Default | locale.Swedish | locale.Turkish -> Error(Nil)",
            "  }",
            "}",
        ]
    )


parts = [HEADER, locale_fn(), dispatcher()]
parts.extend(table_fn(name, doc) for name, doc in TABLES)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(parts) + "\n")

print("wrote", os.path.relpath(OUT, ROOT))
